<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <title>Privacy terms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="about-us-css.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>



  <script type="text/javascript">
    $(document).ready(function(){
        $("#l1").attr('class', 'nav-item');
        $("#k2").attr('class', 'nav-item active');
        $("#m5").attr('class', 'nav-item active');
      });

  </script>
  </head>

  <body>

      <?php include('navbar-main.php'); ?>

      <div class="container">

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="homepage.php">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Privacy terms</li>
          </ol>
        </nav>

        <div class="jumbotron">
          <h1 class="display-4">Privacy / Terms -</h1>
          <hr class="my-4">
          <p>


            <div id="vuukle-powerbar" class="vuukle-powerbar powerbarBoxDiv" style=" " data-styles=""></div>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">PrivacyPolicy</span></strong>
                <br> <span style="color: #000000;">———————</span></p>
            <p style="text-align: justify;">This privacy policy has been compiled to better serve those who are concerned with how their ‘Personally Identifiable&nbsp;<span style="color: #000000;">Information’ (PII) is being used online. PII, as described in US privacy law and information security, is information that </span><span style="color: #000000;">can be used on its own or with other information to identify, contact, or locate a single person, or to identify an </span><span style="color: #000000;">individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect </span>
                <br> <span style="color: #000000;">or otherwise handle your Personally Identifiable Information in accordance with our website.</span><span style="color: #000000;">What personal information do we collect from the people that visit our blog, website? &nbsp;</span><span style="color: #000000;">When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address, phone number or </span><span style="color: #000000;">other details to help you with your experience.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>When do we collect information?</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">We collect information from you when you register on our site, subscribe to a newsletter or enter information on our site.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>How do we use your information?</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a </span><span style="color: #000000;">survey or marketing communication, surf the website, or use certain other site features in the following ways:</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">To personalize your experience and to allow us to deliver the type of content and product offerings in which you are most </span>
                <br> <span style="color: #000000;">interested.</span>
                <br> <span style="color: #000000;">To improve our website in order to better serve you.</span>
                <br> <span style="color: #000000;">To allow us to better service you in responding to your customer service requests.</span>
                <br> <span style="color: #000000;">To send periodic emails regarding your order or other products and services.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>How do we protect your information?</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">We do not use vulnerability scanning and/or scanning to PCI standards.</span>
                <br> <span style="color: #000000;">We only provide articles and information. We never ask for credit card numbers.</span>
                <br> <span style="color: #000000;">We use regular Malware Scanning.</span>
                <br> <span style="color: #000000;">Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have </span>
                <br> <span style="color: #000000;">special access rights to such systems, and are required to keep the information confidential. In addition, all </span>
                <br> <span style="color: #000000;">sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">We implement a variety of security measures when a user enters, submits, or accesses their information to maintain the safety &nbsp;</span><span style="color: #000000;">of your personal information.</span><span style="color: #000000;">All transactions are processed through a gateway provider and are not stored or processed on our servers.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>Do we use ‘cookies’?</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">We do not use cookies for tracking purposes. You can choose to have your computer warn you each time a cookie is being sent, </span><span style="color: #000000;">or you can choose to turn off all cookies. You do this through your browser settings. Since </span>browser<span style="color: #000000;"> is a little different, </span><span style="color: #000000;">look at your browser’s Help Menu to learn the correct way to modify your cookies. If you turn cookies off, some features will </span><span style="color: #000000;">be disabled. that make your site experience more efficient and may not function properly. However, you will still be able to </span><span style="color: #000000;">place orders.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Third-party disclosure</span></strong></p>
            <p style="text-align: justify;"><span style="color: #000000;">We do not sell, trade, or </span>otherwise<span style="color: #000000;"> transfer to outside parties your Personally Identifiable Information unless we provide </span><span style="color: #000000;">users with advance notice. This does not include website hosting partners and other parties who assist us in operating our&nbsp;</span><span style="color: #000000;">website, conducting our business, or serving our users, so long as those parties agree to keep this information confidential.</span><span style="color: #000000;">We may also release information when it’s release is appropriate to comply with the law, enforce our site policies, or </span><span style="color: #000000;">protect ours or others’ rights, property or safety.</span><span style="color: #000000;">However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or </span>
                <br> <span style="color: #000000;">other uses.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Third-party links</span></strong></p>
            <p style="text-align: justify;"><span style="color: #000000;">Occasionally, at our discretion, we may include or offer third-party products or services on our website. These third-party </span><span style="color: #000000;">sites have separate and independent privacy policies. </span>We therefore<span style="color: #000000;"> have no responsibility or liability for the content and </span><span style="color: #000000;">activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about </span><span style="color: #000000;">these sites.</span><span style="color: #000000;">We honor Do Not Track signals and Do Not Track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism </span><span style="color: #000000;">is in place.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>Does our site allow third-party behavioral tracking?</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">It’s also important to note that we do not allow third-party behavioral tracking COPPA (Children Online Privacy Protection </span><span style="color: #000000;">Act) When it comes to the collection of personal information from children under the age of 13 years old, the Children’s </span><span style="color: #000000;">Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, United States’ consumer </span><span style="color: #000000;">protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to </span><span style="color: #000000;">protect children’s privacy and safety online. We do not specifically market to children under the age of 13 years old.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Fair Information Practices</span></strong></p>
            <p style="text-align: justify;"><span style="color: #000000;">The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include </span><span style="color: #000000;">have played a significant role in the development of data protection laws around the globe. Understanding the Fair </span><span style="color: #000000;">Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that </span><span style="color: #000000;">protect personal information.</span><span style="color: #000000;">In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach </span><span style="color: #000000;">occur:</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">We will notify you via email&nbsp;</span><span style="color: #000000;">Within 7 business days</span>
                <br> <span style="color: #000000;">We will notify the users via in-site notification&nbsp;</span><span style="color: #000000;">Within 7 business days&nbsp;</span><span style="color: #000000;">We also agree to the Individual Redress Principle which requires that individuals have the right to legally pursue </span><span style="color: #000000;">enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only </span><span style="color: #000000;">that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government </span><span style="color: #000000;">agencies to investigate and/or prosecute non-compliance by data processors.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>CAN SPAM&nbsp; Act :</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives </span><span style="color: #000000;">recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.</span><span style="color: #000000;">We collect your email address in order to:</span><span style="color: #000000;">Send information, respond to inquiries, and/or other requests or questions To be in accordance with CANSPAM, we agree to the </span><span style="color: #000000;">following:</span>
                <br> <span style="color: #000000;">Not use false or misleading subjects or email addresses.</span>
                <br> <span style="color: #000000;">Identify the message as an advertisement in some reasonable way.</span>
                <br> <span style="color: #000000;">Include the physical address of our business or site headquarters.</span>
                <br> <span style="color: #000000;">Monitor third-party email marketing services for compliance, if one is used.</span><span style="color: #000000;">Honor opt-out/unsubscribe requests quickly.</span><span style="color: #000000;">Allow users to unsubscribe by using the link at the bottom of each email.</span><span style="color: #000000;">If at any time you would like to unsubscribe from receiving future emails, you can email us at </span>follow<span style="color: #000000;"> the instructions at the </span><span style="color: #000000;">bottom of each email. and we will promptly remove you from ALL correspondence.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>Contacting Us</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">If there are any questions regarding this privacy policy, you may contact us using the information below.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">https://ideapreneurindia.com</span>
                <br> sahu<span style="color: #000000;"> Technologies </span>
                <br> <span style="color: #000000;">R-1,L-5,Milind </span>nagar<span style="color: #000000;">,</span>kurla<span style="color: #000000;"> west,Mumbai,</span>maharastra<span style="color: #000000;">, India</span>
                <br> <span style="color: #000000;">ideapreneurindia@gmail.com</span>
                <br> <span style="color: #000000;">info@ideapreneurindia.com</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">disclaimer</span></strong></p>
            <p style="text-align: justify;"><span style="color: #000000;">——————————–</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Terms of Use</span></strong></p>
            <p style="text-align: justify;"><span style="color: #000000;">By using the site as a reader or registered user, you are deemed to have accepted these terms and conditions. If you are </span><span style="color: #000000;">registered as a user, please read carefully the privacy policy.</span><span style="color: #000000;">Any changes we make to the terms and conditions will be reflected on this page. Access to and use of this site </span><span style="color: #000000;">(ideapreneurindia.com) is provided by </span>sahu<span style="color: #000000;"> Technologies. subject to the following terms:</span><span style="color: #000000;">By using ideapreneurindia.com you agree to be legally bound by these terms, which shall take effect immediately on your first </span><span style="color: #000000;">use of ideapreneurindia.com. If you do not agree to be legally bound by all the following terms please do not access and/or </span><span style="color: #000000;">use ideapreneurindia.com.</span><span style="color: #000000;">May change these terms at any time by posting changes online. Please review these terms regularly to ensure you are aware of </span><span style="color: #000000;">any changes made by </span>sahu<span style="color: #000000;"> Technologies. Your continued use of ideapreneurindia.com after changes to this policy are posted </span><span style="color: #000000;">means you agree to be legally bound by these terms as updated and/or amended.</span><span style="color: #000000;">You may not copy, reproduce, republish, download, post, broadcast, transmit, make available to the public, or otherwise use </span><span style="color: #000000;">a derivative work from any ideapreneurindia.com content except for your own personal, non-commercial use. Any </span>other<span style="color: #000000;"> use of </span><span style="color: #000000;">ideapreneurindia.com content requires the prior written permission of SAHU Technologies.</span><span style="color: #000000;">You agree to use ideapreneurindia.com only for lawful purposes, and in a way that does not infringe the rights of, restrict </span><span style="color: #000000;">or inhibit anyone else’s use and enjoyment of Ideapreneurindia.com. Prohibited </span>behavior<span style="color: #000000;"> includes harassing or causing distress or </span><span style="color: #000000;">inconvenience to any person, transmitting obscene or offensive content or disrupting the normal flow of dialogue within </span><span style="color: #000000;">ideapreneurindia.com.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Disclaimer of Liability</span></strong>
                <br> <span style="color: #000000;">—————————</span>
                <br> <span style="color: #000000;">Online Community does not accept any responsibility for any statement in the material. You must not rely on any statement we </span><span style="color: #000000;">have published on ideapreneurindia.com without first taking specialist professional advice. Nothing in the material is </span><span style="color: #000000;">provided for any specific purpose or at the request of any particular person. We give no warranties of any kind and without </span><span style="color: #000000;">any representations for material information, names, images, pictures, logos and icons found in Ideapreneurindia.com.</span><span style="color: #000000;">You can access other sites via links from Ideapreneurindia.com. These sites are not under our control and we are not responsible in </span><span style="color: #000000;">any way for any of their contents.</span>sahu<span style="color: #000000;"> Technologies is not liable for any of the following losses or damages (whether such losses where foreseen, foreseeable, </span>
                <br> <span style="color: #000000;">known or otherwise):</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">Loss of data;</span>
                <br> <span style="color: #000000;">Loss of revenue or anticipated profits;</span>
                <br> <span style="color: #000000;">Loss of business;</span>
                <br> <span style="color: #000000;">Loss of opportunity;</span>
                <br> <span style="color: #000000;">Loss of goodwill or injury to reputation;</span>
                <br> <span style="color: #000000;">losses suffered by third parties; or&nbsp;</span><span style="color: #000000;">any indirect, consequential, special or exemplary damages arising from the use of ideapreneurindia.com regardless of the form </span><span style="color: #000000;">of action.</span><span style="color: #000000;">You must take your own precaution in this respect, as we accept no responsibility for any infection by virus, by other </span><span style="color: #000000;">contamination or by anything that has destructive properties.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">IF YOU’RE UNDER 18:</span></strong></p>
            <p style="text-align: justify;"><span style="color: #000000;">Please get permission from a parent or guardian before taking part in any Ideapreneurindia.com discussion.</span><span style="color: #000000;">Never reveal any personal information about yourself or anyone else (for example, telephone number, home address or email </span><span style="color: #000000;">address).</span><span style="color: #000000;">Third Party Material On ideapreneurindia.com</span><span style="color: #000000;">You will see advertising material submitted by third parties on ideapreneurindia.com. Advertisers are solely responsible for </span><span style="color: #000000;">the content of advertising material, which they submit to us, including ensuring that it complies with relevant legislation.</span><span style="color: #000000;">We accept no responsibility for the content of advertising material, including, without limitation, any error, omission or </span>
                <br> <span style="color: #000000;">inaccuracy therein.</span><span style="color: #000000;">Text Submission To ideapreneurindia.com.</span><span style="color: #000000;">Users of our site may submit material for publication in various areas of the site, including our blog service. We accept no </span><span style="color: #000000;">liability with respect to any material submitted by users and published by us and we are not responsible for its content and </span><span style="color: #000000;">accuracy.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">If you want to submit material to us for publication on ideapreneurindia.com, you may do so on the following terms and </span>
                <br> <span style="color: #000000;">conditions:&nbsp;</span><span style="color: #000000;">Publication of any material you submit to us will be at your sole discretion. We reserve the right to make additions or </span>
                <br> <span style="color: #000000;">deletions to the text or graphics prior to publication, or to refuse publication;</span>
                <br> <span style="color: #000000;">you grant us a non-exclusive, perpetual, royalty-free, worldwide license to republish any material you submit to us in any </span>
                <br> <span style="color: #000000;">format, including, without limitation, print and electronic format;</span>
                <br> <span style="color: #000000;">You declare to us that any material you submit to us is your own original work and that you own the copyright and any other </span>
                <br> <span style="color: #000000;">relevant rights;</span>
                <br> <span style="color: #000000;">You warrant that the material you submit is not obscene, offensive, defamatory of any person or otherwise illegal;</span>
                <br> <span style="color: #000000;">You agree not to post material including spamming which is deliberately intended to upset other users;</span>
                <br> <span style="color: #000000;">you acknowledge that any breach of these warranties may cause us damage or loss and you agree to indemnify us in full and </span>
                <br> <span style="color: #000000;">permanently against any third party liabilities, claims, costs, loss or damage we incur as a result of publishing material </span>
                <br> <span style="color: #000000;">you submit to us, including consequential losses;</span>
                <br> <span style="color: #000000;">We reserve the right to remove your access to individual services if we believe you are abusing the services in any way.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">Graphic Material Submission To ideapreneurindia.com</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">When you send a photograph or other graphical material to us you do so in accordance with these Terms of Use. This means that </span><span style="color: #000000;">you hereby agree that you have taken the photograph(s) you have sent to us or you have permission from or are authorised by </span><span style="color: #000000;">the owner of the photograph(s) to send it (them) to us, and you are granting us a non-exclusive, royalty-free license to </span><span style="color: #000000;">publish or otherwise use the photograph(s) in any way and at any time we want on Ideapreneurindia.com. The photograph(s) must not be </span><span style="color: #000000;">defamatory and may not break any laws.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">Selected photographs and graphical material will be published at the discretion of the editor and you will not be paid, even </span><span style="color: #000000;">if your photograph(s) is (are) published. We may cut, edit, crop or arrange your photograph(s) or graphic as we think fit to </span><span style="color: #000000;">appear on Ideapreneurindia.com, and we may remove your photograph(s) or graphics at any time. Your name will be published alongside </span><span style="color: #000000;">your photograph(s) or graphic, but we may edit or delete any comments, which you submit along with your photograph(s) or </span><span style="color: #000000;">graphic.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;">Safety</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">We advise that you never reveal any personal information about yourself or anyone else (for </span>example:<span style="color: #000000;"> telephone number, home </span><span style="color: #000000;">address or email address). Please do not include postal addresses of any kind. If you have a helpful address to share, inform </span><span style="color: #000000;">the host of the relevant community area using the ‘Contact Us’ link, and they will promote it if they see fit.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>General</strong></span></p>
            <p style="text-align: justify;">———–</p>
            <p style="text-align: justify;"><span style="color: #000000;">These terms may vary from time to time. Please ensure that you review these terms and conditions regularly as you will be </span><span style="color: #000000;">deemed to have accepted any variation if you continue to use the site after it has been posted. Although we will do our best </span><span style="color: #000000;">to provide constant, uninterrupted access to Ideapreneurindia.com, we do not guarantee this. We accept no responsibility or liability </span><span style="color: #000000;">for any interruption or delay.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>Governing Law &amp; Jurisdiction</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">These terms shall be governed by and interpreted in accordance with the laws of India and especially the Information </span><span style="color: #000000;">Technology Act, 2000. All relevant rules, regulations, directions, orders and notifications will also apply.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Terms of Use</span></strong>
                <br> <span style="color: #000000;">——————–</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">By using the site as a reader or registered user, you are deemed to have accepted these terms and conditions. If you are </span><span style="color: #000000;">registered as a user, please read carefully the privacy policy.</span><span style="color: #000000;">Any changes we make to the terms and conditions will be reflected on this page. Access to and use of this site </span><span style="color: #000000;">ideapreneurindia.com) is provided by </span>sahu<span style="color: #000000;"> Technologies. subject to the following terms:</span><span style="color: #000000;">By using ideapreneurindia.com you agree to be legally bound by these terms, which shall take effect immediately on your first </span><span style="color: #000000;">use of ideapreneurindia.com. If you do not agree to be legally bound by all the following terms please do not access and/or </span>
                <br> <span style="color: #000000;">use ideapreneurindia.com.</span><span style="color: #000000;">May change these terms at any time by posting changes online. Please review these terms regularly to ensure you are aware of </span><span style="color: #000000;">any changes made by </span>sahu<span style="color: #000000;"> Technologies. Your continued use of ideapreneurindia.com after changes to this policy are posted </span><span style="color: #000000;">means you agree to be legally bound by these terms as updated and/or amended.</span><span style="color: #000000;">You may not copy, reproduce, republish, download, post, broadcast, transmit, make available to the public, or otherwise use </span><span style="color: #000000;">ideapreneurindia.com content in any way except for your own personal, non-commercial use. You also agree not to adapt, alter </span><span style="color: #000000;">or create a derivative work from any ideapreneurindia.com content except for your own personal, non-commercial use. Any </span>other&nbsp;<span style="color: #000000;">use of ideapreneurindia.com content requires the prior written permission of </span>sahu<span style="color: #000000;"> Technologies.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">You agree to use ideapreneurindia.com only for lawful purposes, and in a way that does not infringe the rights of, restrict </span><span style="color: #000000;">or inhibit anyone else’s use and enjoyment of ideapreneurindia.com. Prohibited </span>behaviour<span style="color: #000000;"> includes harassing or causing </span><span style="color: #000000;">distress or inconvenience to any person, transmitting obscene or offensive content or disrupting the normal flow of dialogue </span><span style="color: #000000;">within ideapreneurindia.com.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Disclaimer of Liability</span></strong>
                <br> <span style="color: #000000;">——————————-</span>
                <br> <span style="color: #000000;">Online Community does not accept any responsibility for any statement in the material. You must not rely on any statement we </span><span style="color: #000000;">have published on ideapreneurindia.com without first taking specialist professional advice. Nothing in the material is&nbsp;</span><span style="color: #000000;">provided for any specific purpose or at the request of any particular person. We give no warranties of any kind and without </span><span style="color: #000000;">any representations for material information, names, images, pictures, logos and icons found in ideapreneurindia.com.</span><span style="color: #000000;">You can access other sites via links from Ideapreneurindia.com. These sites are not under our control and we are not responsible in </span><span style="color: #000000;">any way for any of their contents.</span></p>
            <p style="text-align: justify;">sahu<span style="color: #000000;"> Technologies is not liable for any of the following losses or damages (whether such losses where foreseen, foreseeable, </span><span style="color: #000000;">known or otherwise):</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">Loss of data;</span>
                <br> <span style="color: #000000;">Loss of revenue or anticipated profits;</span>
                <br> <span style="color: #000000;">Loss of business;</span>
                <br> <span style="color: #000000;">Loss of opportunity;</span>
                <br> <span style="color: #000000;">Loss of goodwill or injury to reputation;</span>
                <br> <span style="color: #000000;">losses suffered by third parties; or&nbsp;</span><span style="color: #000000;">any indirect, consequential, special or exemplary damages arising from the use of ideapreneurindia.com regardless of the form </span><span style="color: #000000;">of action.You must take your own precaution in this respect, as we accept no responsibility for any infection by virus, by </span><span style="color: #000000;">other contamination or by anything that has destructive properties.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">IF YOU’RE UNDER 18:</span></strong></p>
            <p style="text-align: justify;"><span style="color: #000000;">Please get permission from a parent or guardian before taking part in any ideapreneurindia.com discussion.</span><span style="color: #000000;">Never reveal any personal information about yourself or anyone else (for example, telephone number, home address or email </span>
                <br> <span style="color: #000000;">address).</span><span style="color: #000000;">Third Party Material On ideapreneurindia.com</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">You will see advertising material submitted by third parties on ideapreneurindia.com. Advertisers are solely responsible for </span><span style="color: #000000;">the content of advertising material, which they submit to us, including ensuring that it complies with relevant legislation. </span><span style="color: #000000;">We accept no responsibility for the content of advertising material, including, without limitation, any error, omission or </span><span style="color: #000000;">inaccuracy therein.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">Text Submission To ideapreneurindia.com</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">Users of our site may submit material for publication in various areas of the site, including our blog service. We accept no </span><span style="color: #000000;">liability with respect to any material submitted by users and published by us and we are not responsible for its content and </span>
                <br> <span style="color: #000000;">accuracy.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">If you want to submit material to us for publication on ideapreneurindia.com, you may do so on the following terms and </span><span style="color: #000000;">conditions:</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">Publication of any material you submit to us will be at your sole discretion. We reserve the right to make additions or </span>
                <br> <span style="color: #000000;">deletions to the text or graphics prior to publication, or to refuse publication;</span>
                <br> <span style="color: #000000;">you grant us a non-exclusive, perpetual, royalty-free, worldwide license to republish any material you submit to us in any </span>
                <br> <span style="color: #000000;">format, including, without limitation, print and electronic format;</span>
                <br> <span style="color: #000000;">You declare to us that any material you submit to us is your own original work and that you own the copyright and any other </span>
                <br> <span style="color: #000000;">relevant rights;</span>
                <br> <span style="color: #000000;">You warrant that the material you submit is not obscene, offensive, defamatory of any person or otherwise illegal;</span>
                <br> <span style="color: #000000;">You agree not to post material including spamming which is deliberately intended to upset other users;</span>
                <br> <span style="color: #000000;">you acknowledge that any breach of these warranties may cause us damage or loss and you agree to indemnify us in full and </span>
                <br> <span style="color: #000000;">permanently against any third party liabilities, claims, costs, loss or damage we incur as a result of publishing material </span>
                <br> <span style="color: #000000;">you submit to us, including consequential losses;</span>
                <br> <span style="color: #000000;">We reserve the right to remove your access to individual services if we believe you are abusing the services in any way.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">Graphic Material Submission To ideapreneurindia.com.</span><span style="color: #000000;">When you send a photograph or other graphical material to us you do so in accordance with these Terms of Use. This means that </span><span style="color: #000000;">you hereby agree that you have taken the photograph(s) you have sent to us or you have permission from or are authorised by </span><span style="color: #000000;">the owner of the photograph(s) to send it (them) to us, and you are granting us a non-exclusive, royalty-free license to </span><span style="color: #000000;">publish or otherwise use the photograph(s) in any way and at any time we want on ideapreneurindia.com. The photograph(s) must </span><span style="color: #000000;">not be defamatory and may not break any laws.</span><span style="color: #000000;">Selected photographs and graphical material will be published at the discretion of the editor and you will not be paid, even </span><span style="color: #000000;">if your photograph(s) is (are) published. We may cut, edit, crop or arrange your photograph(s) or graphic as we think fit to </span><span style="color: #000000;">appear on ideapreneurindia.com, and we may remove your photograph(s) or graphics at any time. Your name will be published </span>
                <br> <span style="color: #000000;">alongside your photograph(s) or graphic, but we may edit or delete any comments, which you submit along with your photograph </span><span style="color: #000000;">(s) or graphic.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Safety</span></strong>
                <br> <span style="color: #000000;">————</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">We advise that you never reveal any personal information about yourself or anyone else (for </span>example:<span style="color: #000000;"> telephone number, home </span><span style="color: #000000;">address or email address). Please do not include postal addresses of any kind. If you have a helpful address to share, inform </span><span style="color: #000000;">the host of the relevant community area using the ‘Contact Us’ link, and they will promote it if they see fit.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>General</strong></span>
                <br> <span style="color: #000000;">—————-</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">These terms may vary from time to time. Please ensure that you review these terms and conditions regularly as you will be </span><span style="color: #000000;">deemed to have accepted any variation if you continue to use the site after it has been posted. Although we will do our best </span><span style="color: #000000;">to provide constant, uninterrupted access to ideapreneurindia.com we do not guarantee this. We accept no responsibility or </span><span style="color: #000000;">liability for any interruption or delay.</span></p>
            <p style="text-align: justify;"><strong><span style="color: #ff0000;">Governing Law &amp; Jurisdiction</span></strong>
                <br> <span style="color: #000000;">———————————–</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">These terms shall be governed by and interpreted in accordance with the laws of India and especially the Information </span><span style="color: #000000;">Technology Act, 2000. All relevant rules, regulations, directions, orders and notifications will also apply.</span></p>
            <p style="text-align: justify;"><span style="color: #ff0000;"><strong>Contacting Us</strong></span></p>
            <p style="text-align: justify;"><span style="color: #000000;">If there are any questions regarding this privacy policy, you may contact us using the information below.</span></p>
            <p style="text-align: justify;"><span style="color: #000000;">https://ideapreneurindia.com</span>
                <br> sahu<span style="color: #000000;"> Technologies </span>
                <br> <span style="color: #000000;">R-1,L-5,Milind </span>nagar<span style="color: #000000;">,</span>kurla<span style="color: #000000;"> west,Mumbai,</span>maharastra<span style="color: #000000;">, India</span>
                <br> <span style="color: #000000;">ideapreneurindia@gmail.com</span>
                <br> <span style="color: #000000;">info@ideapreneurindia.com</span></p>
            <div id="vuukle-emote" style="max-width:600px" class="emotesBoxDiv"></div>

            </p>

        </div>

      </div>
      <div class="row-fluid">
        <?php include('footer.php'); ?>
      </div>


      <!-- this is font awesome link for adding icons in navbar -->
      <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>

</html>
